export const productsActionType = {
  FETCH_PRODUCTS_REQUEST: 'FETCH_PRODUCT_REQUEST',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCT_FAILED',
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS'
}
